name: Build and package TYPE_SEMVER plugin

on:
  push:
    branches:
      - main
    tags:
      - "v*"

  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: lefred/mariadb-plugin-ci/.github/workflows/build-plugin.yml@main
    with:
      plugin_name: type-semver
      plugin_directory: type_semver
      build_target: type_semver
      plugin_library: type_semver.so

      sdk_image: quay.io/lefred14/mariadb-plugin-build
      mariadb_versions: |
          13.0.2
          13.1.1
          
      cmake_options: -DPLUGIN_DATE_EXTRA=DYNAMIC
      test_suite: type_semver
      run_tests: false
